version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: habixa_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: habixa_user
      POSTGRES_PASSWORD: habixa_password
      POSTGRES_DB: habixa_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - habixa_network

  redis:
    image: redis:7-alpine
    container_name: habixa_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - habixa_network

networks:
  habixa_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
